apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-w08e1 # 👈 match service naming
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: wk08acr40890.azurecr.io/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-w08e1
  labels:
    app: frontend
spec:
  type: LoadBalancer
  loadBalancerIP: 4.237.181.227 # 👈 bind to reserved static IP
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
